name: Test benchmarks TPCC

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    
    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install virtualenv
      run: |
        pip3 install virtualenv

    - name: Set up virtualenv
      run: |
        virtualenv --python=python3.7 benchmark
        source benchmark/bin/activate

    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install ansible dependencies
      run: |
        cd ansible
        ansible-galaxy install cloudalchemy.node_exporter
        ansible-galaxy install cloudalchemy.prometheus

    - name: Test TPCC
      run: |
        echo "should test here"
