name: Unit Test bench_cli

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    
    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install virtualenv
      run: |
        pip3 install virtualenv

    - name: Set up virtualenv
      run: |
        virtualenv --python=python3.7 benchmark
        source benchmark/bin/activate

    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Test
      run: |
        python -m unittest discover -s test -v